/** @type {import('tailwindcss').Config} */
// 源力设计库语义色
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          hover: "var(--primary-hover)",
          active: "var(--primary-active)",
          muted: "var(--primary-muted)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        success: {
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
          muted: "var(--success-muted)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
          muted: "var(--warning-muted)",
        },
        danger: {
          DEFAULT: "var(--danger)",
          foreground: "var(--danger-foreground)",
          muted: "var(--danger-muted)",
        },
        log: {
          DEFAULT: "var(--log-bg)",
          foreground: "var(--log-text)",
        },
        // 源力扩展色
        text1: "var(--text-1)",
        text2: "var(--text-2)",
        text3: "var(--text-3)",
        text4: "var(--text-4)",
        bg1: "var(--bg-1)",
        bg2: "var(--bg-2)",
        bg3: "var(--bg-3)",
        bg4: "var(--bg-4)",
        bg5: "var(--bg-5)",
        border1: "var(--border-1)",
        border2: "var(--border-2)",
        rowhover: "var(--row-hover)",
        rowstripe: "var(--row-stripe)",
        // 源力色阶
        "primary-1": "var(--primary-1)",
        "primary-2": "var(--primary-2)",
        "primary-3": "var(--primary-3)",
        "primary-4": "var(--primary-4)",
        "primary-5": "var(--primary-5)",
        "primary-6": "var(--primary-6)",
        "primary-7": "var(--primary-7)",
        "primary-8": "var(--primary-8)",
        "success-1": "var(--success-1)",
        "success-2": "var(--success-2)",
        "success-3": "var(--success-3)",
        "success-4": "var(--success-4)",
        "success-5": "var(--success-5)",
        "success-6": "var(--success-6)",
        "success-7": "var(--success-7)",
        "success-8": "var(--success-8)",
        "warning-1": "var(--warning-1)",
        "warning-2": "var(--warning-2)",
        "warning-3": "var(--warning-3)",
        "warning-4": "var(--warning-4)",
        "warning-5": "var(--warning-5)",
        "warning-6": "var(--warning-6)",
        "warning-7": "var(--warning-7)",
        "warning-8": "var(--warning-8)",
        "danger-1": "var(--danger-1)",
        "danger-2": "var(--danger-2)",
        "danger-3": "var(--danger-3)",
        "danger-4": "var(--danger-4)",
        "danger-5": "var(--danger-5)",
        "danger-6": "var(--danger-6)",
        "danger-7": "var(--danger-7)",
        "danger-8": "var(--danger-8)",
        "teal-1": "var(--teal-1)",
        "teal-2": "var(--teal-2)",
        "teal-3": "var(--teal-3)",
        "teal-4": "var(--teal-4)",
        "teal-5": "var(--teal-5)",
        "teal-6": "var(--teal-6)",
        "teal-7": "var(--teal-7)",
        "teal-8": "var(--teal-8)",
        "violet-1": "var(--violet-1)",
        "violet-2": "var(--violet-2)",
        "violet-3": "var(--violet-3)",
        "violet-4": "var(--violet-4)",
        "violet-5": "var(--violet-5)",
        "violet-6": "var(--violet-6)",
        "violet-7": "var(--violet-7)",
        "violet-8": "var(--violet-8)",
        "link-1": "var(--link-1)",
        "link-2": "var(--link-2)",
        "link-3": "var(--link-3)",
        "link-4": "var(--link-4)",
        "link-5": "var(--link-5)",
        "link-6": "var(--link-6)",
        "link-7": "var(--link-7)",
        "link-8": "var(--link-8)",
        "grey-1": "var(--grey-1)",
        "grey-2": "var(--grey-2)",
        "grey-3": "var(--grey-3)",
        "grey-4": "var(--grey-4)",
        "grey-5": "var(--grey-5)",
        "grey-6": "var(--grey-6)",
        "grey-7": "var(--grey-7)",
        "grey-8": "var(--grey-8)",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
      fontSize: {
        xs: ["12px", "20px"],
        sm: ["13px", "22px"],
        base: ["14px", "22px"],
        lg: ["16px", "24px"],
        xl: ["18px", "26px"],
        "2xl": ["20px", "28px"],
        "3xl": ["24px", "32px"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(6px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "page-in": {
          from: { opacity: "0", transform: "translateY(8px) scale(0.985)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "page-out": {
          from: { opacity: "1", transform: "translateY(0) scale(1)" },
          to: { opacity: "0", transform: "translateY(-4px) scale(0.995)" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-scale": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "pulse-slow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.28s cubic-bezier(0.16, 1, 0.3, 1)",
        "page-in": "page-in 0.32s cubic-bezier(0.16, 1, 0.3, 1)",
        "fade-in-up": "fade-in-up 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "fade-in-scale": "fade-in-scale 0.2s cubic-bezier(0.16, 1, 0.3, 1)",
        "pulse-slow": "pulse-slow 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 2s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
